from __future__ import annotations

from pydantic import BaseModel, Field


class AnomalyEvent(BaseModel):
    """A spacecraft anomaly that data products may reference.

    Represents mission truth: an event that has occurred on the spacecraft.
    AI will eventually reason about the implications of an anomaly and help
    prioritize the data products that describe or diagnose it, but the
    anomaly itself — its subsystem, severity, and detection time — is a
    mission fact and must not be AI-generated.

    Data products link to an anomaly via their ``anomaly_id`` field.
    The inverse direction is represented by ``related_product_ids``.
    """

    anomaly_id: str = Field(
        description="Unique identifier for this anomaly event, e.g. 'ANOM-017'"
    )
    subsystem: str = Field(
        description=(
            "The spacecraft subsystem affected by this anomaly, "
            "e.g. 'propulsion', 'power', 'thermal', 'communications'"
        )
    )
    severity: float = Field(
        ge=0.0, le=1.0,
        description=(
            "Mission-truth severity of the anomaly [0, 1]. "
            "0.0 = negligible; 1.0 = extremely severe. "
            "This value is provided by the scenario, NOT generated by AI."
        )
    )
    detected_at_s: float = Field(
        ge=0.0,
        description="Simulation-relative time (seconds) when the anomaly was first detected"
    )
    description: str = Field(
        description=(
            "Human-readable description of the anomaly. "
            "Used by AI reasoning to understand the nature and context of the event, "
            "e.g. 'Unexpected vibration detected in primary propulsion assembly.'"
        )
    )
    status: str = Field(
        description=(
            "Current status of the anomaly, e.g. 'active', 'resolved', 'monitoring'. "
            "A free-form string — not constrained to an enum."
        )
    )
    related_product_ids: list[str] = Field(
        default_factory=list,
        description=(
            "IDs of data products that can help diagnose or understand this anomaly. "
            "These products typically have their anomaly_id set to this anomaly's anomaly_id."
        )
    )
